import { useState, useMemo, ChangeEvent, useRef } from "react";
import {
  AutoComplete,
  Drawer,
  Space,
  Tag,
  Progress,
  Table,
  Input,
  Popconfirm,
  Tabs,
  message,
} from "antd";
import {
  LandPlot,
  Swords,
  CheckCircle2,
  Plus,
  Search,
  Trash2,
  RotateCcw,
  Sparkles,
  Bot,
  Users,
  FileText,
  Download,
  Upload,
} from "lucide-react";

import { QButton } from "@/components/ui/button";
import { COLORS } from "../settings/consts/color";
import { AntdThemeConfig } from "@/components/ui/antd-config";
import { QSelect } from "@/components/ui/select";
import { useTournamentStore } from "@/store/match";
import { useParticipantsByTournamentID } from "../players/hooks";
import type { Participant, TournamentParticipant } from "@gd/proto/participant/v1/participant_pb";

// Danh họ và tên đệm phổ biến ở Việt Nam
const HO = [
  "Nguyễn",
  "Trần",
  "Lê",
  "Phạm",
  "Hoàng",
  "Huỳnh",
  "Vũ",
  "Võ",
  "Đặng",
  "Bùi",
  "Đỗ",
  "Hồ",
  "Ngô",
  "Dương",
  "Lý",
];
const TEN_DEM = [
  "Văn",
  "Thị",
  "Đức",
  "Minh",
  "Anh",
  "Quang",
  "Hữu",
  "Thái",
  "Gia",
  "Đình",
  "Thành",
  "Bảo",
  "Tuấn",
  "Hoàng",
  "Thanh",
];
const TEN = [
  "An",
  "Bình",
  "Cường",
  "Dũng",
  "Đạt",
  "Hải",
  "Hùng",
  "Huy",
  "Khoa",
  "Lâm",
  "Nam",
  "Phong",
  "Phúc",
  "Quân",
  "Sơn",
  "Tâm",
  "Thắng",
  "Thịnh",
  "Trung",
  "Tuấn",
  "Tùng",
  "Vinh",
  "Việt",
  "Vũ",
];

// Hàm sinh danh sách 256 VĐV không trùng lặp name hoàn toàn (kèm STT đằng sau cho dễ nhìn)
export const PLAYERS_DATA = Array.from({ length: 256 }, (_, index) => {
  const h = HO[index % HO.length];
  const d = TEN_DEM[(index * 3) % TEN_DEM.length];
  const t = TEN[(index * 7) % TEN.length];

  return {
    value: `${h} ${d} ${t} (#${index + 1})`,
  };
});

interface MatchItem {
  id: string;
  matchNo: number;
  playerA: string;
  playerB: string;
  isAutoGenerated?: boolean;
  A: TournamentParticipant,
  B: TournamentParticipant,
}

export const FirstMatchRoundSetting = () => {
  const { id } = useTournamentStore();

  const { data } = useParticipantsByTournamentID({
    tournamentId: id,
  });

  const participants = data?.tournamentParticipants ?? [];

  console.log("participants", participants);

  const [open, setOpen] = useState(false);

  // Quy mô giải đấu
  const TOTAL_PLAYERS = participants.length;
  const TOTAL_MATCHES_NEEDED = Math.floor(TOTAL_PLAYERS / 2);

  const byeNumber = TOTAL_PLAYERS % 2 === 0 ? 0 : 1;

  // Form state thủ công
  const [playerA, setPlayerA] = useState<string>("");
  const [playerB, setPlayerB] = useState<string>("");

  // Tìm kiếm & Danh sách trận đã chọn
  const [searchText, setSearchText] = useState("");
  const [createdMatches, setCreatedMatches] = useState<MatchItem[]>([]);

  const fileInputRef = useRef<HTMLInputElement>(null);

  // Tập hợp danh sách VĐV ĐÃ ĐƯỢC CHỌN (để tránh chọn trùng)
  const usedPlayers = useMemo(() => {
    const set = new Set<string>();
    createdMatches.forEach((m) => {
      set.add(m.playerA);
      set.add(m.playerB);
    });
    return set;
  }, [createdMatches]);

  // Kiểm tra VĐV đang nhập có bị trùng không
  const isPlayerAUsed = usedPlayers.has(playerA);
  const isPlayerBUsed = usedPlayers.has(playerB);
  const isSamePlayer = playerA && playerB && playerA === playerB;

  // 1. MỤC TẠO TỰ ĐỘNG TOÀN BỘ 100% (Xóa cũ, tự động ghép lại từ đầu)
  const handleGenerateAllAuto = () => {
    const shuffled = [...participants].sort(() => Math.random() - 0.5);

    console.log("shuffled", shuffled);
    const newMatches: MatchItem[] = [];

    for (let i = 0; i < shuffled.length - 1; i += 2) {
      newMatches.push({
        id: `auto-all-${Date.now()}-${i}`,
        matchNo: newMatches.length + 1,
        playerA: `${shuffled[i].displayName} (${shuffled[i].id.substring(shuffled[i].id.length - 4, shuffled[i].id.length)})`,
        playerB: `${shuffled[i + 1].displayName} (${shuffled[i + 1].id.substring(shuffled[i + 1].id.length - 4, shuffled[i + 1].id.length)})`,
        A: shuffled[i],
        B: shuffled[i + 1],
        isAutoGenerated: true,
      });
    }

    setCreatedMatches(newMatches);
  };

  // 2. MỤC TẠO TỰ ĐỘNG CHO CÁC CƠ THỦ CÒN LẠI (Trong tab kết hợp)
  const handleAutoGenerateRemaining = () => {
    const availablePlayers = PLAYERS_DATA.filter(
      (p) => !usedPlayers.has(p.value),
    );
    if (availablePlayers.length < 2) return;

    const shuffled = [...availablePlayers].sort(() => Math.random() - 0.5);
    const newMatches: MatchItem[] = [];

    for (let i = 0; i < shuffled.length - 1; i += 2) {
      newMatches.push({
        id: `auto-rem-${Date.now()}-${i}`,
        matchNo: createdMatches.length + newMatches.length + 1,
        playerA: shuffled[i].value,
        playerB: shuffled[i + 1].value,
        A: shuffled[i],
        B: shuffled[i + 1]
      });
    }

    setCreatedMatches([...newMatches, ...createdMatches]);
  };

  // 3. THÊM TRẬN THỦ CÔNG
  const handleAddMatch = () => {
    if (!playerA || !playerB || isPlayerAUsed || isPlayerBUsed || isSamePlayer)
      return;

    const newMatch: MatchItem = {
      id: Date.now().toString(),
      matchNo: createdMatches.length + 1,
      playerA,
      playerB,
      isAutoGenerated: false,
    };

    setCreatedMatches([newMatch, ...createdMatches]);
    setPlayerA("");
    setPlayerB("");
  };

  // 4. CHỨC NĂNG EXPORT FILE TXT DANH SÁCH VĐV
  const handleExportTxt = () => {
    // Xuất danh sách VĐV chưa xếp trận (hoặc toàn bộ nếu chưa ai xếp)
    const availablePlayers = PLAYERS_DATA.filter(
      (p) => !usedPlayers.has(p.value),
    ).map((p) => p.value);

    const playersToExport =
      availablePlayers.length > 0
        ? availablePlayers
        : PLAYERS_DATA.map((p) => p.value);

    const content = playersToExport.join("\n");
    const blob = new Blob([content], { type: "text/plain;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.download = "danh_sach_vdv.txt";
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
    message.success("Đã xuất file danh sách VĐV thành công!");
  };

  // 5. CHỨC NĂNG IMPORT FILE TXT VÀ TỰ ĐỘNG XẾP CẶP
  const handleImportTxt = (e: ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;

    const reader = new FileReader();
    reader.onload = (event) => {
      const text = event.target?.result as string;
      if (!text) return;

      // Đọc từng dòng, xoá khoảng trắng thừa và dòng trống
      const lines = text
        .split(/\r?\n/)
        .map((line) => line.trim())
        .filter((line) => line.length > 0);

      if (lines.length < 2) {
        message.error("File text cần có ít nhất 2 VĐV để ghép trận!");
        return;
      }

      const newMatches: MatchItem[] = [];
      let currentMatchNo = createdMatches.length + 1;

      // Ghép cứ 2 dòng liên tiếp thành 1 trận
      for (let i = 0; i < lines.length - 1; i += 2) {
        newMatches.push({
          id: `file-import-${Date.now()}-${i}`,
          matchNo: currentMatchNo++,
          playerA: lines[i],
          playerB: lines[i + 1],
        });
      }

      setCreatedMatches((prev) => [...newMatches, ...prev]);
      message.success(`Đã thêm thành công ${newMatches.length} trận từ file!`);

      // Reset value của input file
      e.target.value = "";
    };

    reader.readAsText(file);
  };

  const handleDeleteMatch = (id: string) => {
    const updated = createdMatches
      .filter((m) => m.id !== id)
      .map((m, idx) => ({ ...m, matchNo: createdMatches.length - idx }));
    setCreatedMatches(updated);
  };

  // Lọc danh sách trận theo từ khóa tìm kiếm
  const filteredMatches = useMemo(() => {
    if (!searchText) return createdMatches;
    const kw = searchText.toLowerCase();
    return createdMatches.filter(
      (m) =>
        m.playerA.toLowerCase().includes(kw) ||
        m.playerB.toLowerCase().includes(kw) ||
        `#${m.matchNo}`.includes(kw),
    );
  }, [createdMatches, searchText]);

  const columns = [
    {
      title: "Trận",
      dataIndex: "matchNo",
      key: "matchNo",
      width: 80,
      render: (num: number) => <Tag>#{num}</Tag>,
    },
    {
      title: "Cơ thủ A",
      dataIndex: "playerA",
      key: "playerA",
      render: (text: string) => (
        <span className="font-semibold text-blue-400">{text}</span>
      ),
    },
    {
      title: "VS",
      key: "vs",
      width: 50,
      render: () => (
        <span className="text-[10px] font-black text-amber-500">VS</span>
      ),
    },
    {
      title: "Cơ thủ B",
      dataIndex: "playerB",
      key: "playerB",
      render: (text: string) => (
        <span className="font-semibold text-rose-400">{text}</span>
      ),
    },
    {
      title: "",
      key: "action",
      width: 50,
      render: (_: any, record: MatchItem) => (
        <QButton
          type="text"
          danger
          size="small"
          icon={<Trash2 size={14} />}
          onClick={() => handleDeleteMatch(record.id)}
        />
      ),
    },
  ];

  return (
    <AntdThemeConfig>
      <QButton
        icon={<LandPlot size={16} style={{ color: COLORS.green }} />}
        size="large"
        style={{
          height: "auto",
          display: "inline-flex",
          alignItems: "center",
          gap: 10,
          padding: "10px 20px",
          borderRadius: 12,
          fontWeight: 700,
          fontSize: 13,
          color: "#ffffff",
          border: `1px solid ${COLORS.border}`,
          background: "linear-gradient(135deg, #1a1d27, #22263a)",
          boxShadow: "0 4px 16px rgba(0,0,0,0.4)",
        }}
        onClick={() => setOpen(true)}
      >
        Ghép cặp thi đấu ({createdMatches.length}/{TOTAL_MATCHES_NEEDED})
      </QButton>

      <Drawer
        title={
          <div className="flex items-center gap-2">
            <Swords size={20} className="text-amber-500" />
            <span>
              Tạo cặp đấu thi đấu (
              <span className="font-semibold text-emerald-400">
                {TOTAL_PLAYERS}
              </span>{" "}
              Cơ thủ - Miễn vòng đầu{" "}
              <span className="font-semibold text-emerald-400">
                {byeNumber}
              </span>
              )
            </span>
          </div>
        }
        placement="right"
        size={900}
        open={open}
        onClose={() => setOpen(false)}
        extra={
          <QButton
            onClick={() => setOpen(false)}
            size="large"
            icon={<Users size={16} className="!text-white stroke-[2.5]" />}
            style={{
              height: "auto",
              display: "inline-flex",
              alignItems: "center",
              gap: 10,
              padding: "10px 20px",
              borderRadius: 12,
              fontWeight: 700,
              fontSize: 13,
              color: "white",
              border: "1px solid #6ee7b7",
              background: "linear-gradient(135deg, #10b981, #059669)",
              boxShadow: "0 4px 20px rgba(16, 185, 129, 0.4)",
              cursor: "pointer",
              transition: "all 0.2s ease-in-out",
            }}
          >
            Xác nhận ({createdMatches.length}/{TOTAL_MATCHES_NEEDED} Trận)
          </QButton>
        }
      >
        <div className="flex flex-col gap-5">
          {/* 1. ĐẾM TIẾN ĐỘ */}
          <div className="p-4 rounded-xl border border-slate-800 bg-slate-900/60 flex flex-col gap-2">
            <div className="flex justify-between items-center text-xs font-semibold">
              <span className="text-slate-300">Đã ghép cặp:</span>
              <span className="text-amber-400 font-bold text-sm">
                {createdMatches.length} / {TOTAL_MATCHES_NEEDED} Trận
              </span>
            </div>
            <Progress
              percent={Math.round(
                (createdMatches.length / TOTAL_MATCHES_NEEDED) * 100,
              )}
              strokeColor={{ "0%": "#f59e0b", "100%": "#10b981" }}
              showInfo={false}
            />
          </div>

          {/* 2. KHU VỰC PHÂN CHIA TẠO TRẬN (TỰ ĐỘNG vs PHỐI HỢP vs FILE TEXT) */}
          <div className="p-4 rounded-xl border border-slate-800 bg-slate-900/40">
            <Tabs
              defaultActiveKey="auto_all"
              items={[
                {
                  key: "auto_all",
                  label: (
                    <span className="flex items-center gap-1.5 font-semibold text-xs">
                      <Bot size={15} className="text-purple-400" /> Tạo tự động
                      100%
                    </span>
                  ),
                  children: (
                    <>
                      <div className="flex items-center gap-3 pt-2">
                        <div className="flex-1">
                          <label className="block text-xs text-slate-400 mb-2">
                            Thiết lập thuật toán
                          </label>
                          <QSelect
                            size="large"
                            value="random"
                            className="w-full"
                            disabled
                            options={[
                              {
                                value: "random",
                                label: "Bốc thăm ngẫu nhiên hoàn toàn",
                              },
                              {
                                value: "seed",
                                label: "Chia đều hạt giống & Chặn cùng CLB",
                              },
                            ]}
                          />
                        </div>
                        <Popconfirm
                          title="Tự động bốc thăm lại?"
                          description="Hành động này sẽ ghi đè lại toàn bộ các trận đã tạo trước đó."
                          onConfirm={handleGenerateAllAuto}
                          okText="Đồng ý"
                          cancelText="Hủy"
                        >
                          <QButton
                            type="primary"
                            icon={<Sparkles size={14} />}
                            className="bg-purple-600 hover:bg-purple-500 h-10 mt-5 font-bold"
                          >
                            Tạo tự động toàn bộ giải
                          </QButton>
                        </Popconfirm>
                      </div>
                      <p className="mt-2 text-[13px] font-medium leading-relaxed text-slate-400 italic">
                        <span className="font-semibold text-emerald-400">
                          Tính minh bạch:
                        </span>{" "}
                        Kết quả được hệ thống tự động tạo ngẫu nhiên và không
                        thể bị can thiệp hoặc chỉnh sửa, kể cả bởi nhà phát
                        triển.
                      </p>
                    </>
                  ),
                },
                {
                  key: "hybrid",
                  label: (
                    <span className="flex items-center gap-1.5 font-semibold text-xs">
                      <Users size={15} className="text-amber-400" /> Ghép kết
                      hợp (Thủ công + Tự động)
                    </span>
                  ),
                  children: (
                    <div className="flex flex-col gap-3 pt-2">
                      <div className="grid grid-cols-2 gap-3">
                        <div>
                          <label className="block text-xs font-semibold text-slate-400 mb-1">
                            Cơ thủ A
                          </label>
                          <AutoComplete
                            size="large"
                            className="w-full"
                            placeholder="Nhập tên cơ thủ A..."
                            options={PLAYERS_DATA}
                            value={playerA}
                            onChange={setPlayerA}
                            status={isPlayerAUsed ? "error" : ""}
                          />
                          {isPlayerAUsed && (
                            <span className="text-[11px] text-rose-500 mt-1 block">
                              Cơ thủ này đã có trận!
                            </span>
                          )}
                        </div>

                        <div>
                          <label className="block text-xs font-semibold text-slate-400 mb-1">
                            Cơ thủ B
                          </label>
                          <AutoComplete
                            size="large"
                            className="w-full"
                            placeholder="Nhập tên cơ thủ B..."
                            options={PLAYERS_DATA}
                            value={playerB}
                            onChange={setPlayerB}
                            status={
                              isPlayerBUsed || isSamePlayer ? "error" : ""
                            }
                          />
                          {isPlayerBUsed && (
                            <span className="text-[11px] text-rose-500 mt-1 block">
                              Cơ thủ này đã có trận!
                            </span>
                          )}
                          {isSamePlayer && (
                            <span className="text-[11px] text-rose-500 mt-1 block">
                              Không thể chọn trùng người!
                            </span>
                          )}
                        </div>
                      </div>

                      <div className="grid grid-cols-2 gap-3 mt-1">
                        <QButton
                          type="primary"
                          disabled={
                            !playerA ||
                            !playerB ||
                            isPlayerAUsed ||
                            isPlayerBUsed ||
                            isSamePlayer
                          }
                          icon={<Plus size={16} />}
                          onClick={handleAddMatch}
                          className="bg-amber-600 hover:bg-amber-500 w-full"
                        >
                          Thêm trận thủ công
                        </QButton>

                        <QButton
                          type="default"
                          icon={
                            <Sparkles size={16} className="text-purple-400" />
                          }
                          onClick={handleAutoGenerateRemaining}
                          className="w-full border-purple-500/40 text-purple-300 hover:text-purple-200 hover:border-purple-400"
                        >
                          Ghép tự động các người còn lại
                        </QButton>
                      </div>
                    </div>
                  ),
                },
                {
                  key: "text_file",
                  label: (
                    <span className="flex items-center gap-1.5 font-semibold text-xs">
                      <FileText size={15} className="text-blue-400" /> Ghép qua
                      File Text
                    </span>
                  ),
                  children: (
                    <div className="flex flex-col gap-4 pt-2">
                      {/* Hint Box hướng dẫn */}
                      <div className="p-3 rounded-lg bg-blue-950/40 border border-blue-500/30 text-xs text-slate-300 leading-relaxed">
                        <p className="font-semibold text-blue-400 mb-1 flex items-center gap-1">
                          💡 Gợi ý livestream/bốc thăm công khai:
                        </p>
                        1. Nhấn <b className="text-slate-100">Export TXT</b> để
                        tải danh sách VĐV.
                        <br />
                        2. Dán danh sách vào các trang quay số 3rd party (như{" "}
                        <span className="text-amber-400 font-semibold">
                          Wheel of Names, Spin the Wheel...
                        </span>
                        ) để quay trực tiếp.
                        <br />
                        3. Copy kết quả sau khi quay xong vào một file `.txt`
                        (mỗi VĐV một dòng).
                        <br />
                        4. Nhấn <b className="text-slate-100">Import TXT</b> bên
                        dưới, hệ thống sẽ tự động ghép từng 2 dòng liên tiếp
                        thành 1 trận đấu.
                      </div>

                      {/* Nút Export & Import */}
                      <div className="grid grid-cols-2 gap-3">
                        <QButton
                          onClick={handleExportTxt}
                          size="large"
                          icon={
                            <Download size={16} className="text-blue-400" />
                          }
                          className="group transition-all duration-200 hover:!border-emerald-400/60 hover:!bg-emerald-400/[0.06] hover:!text-emerald-400 hover:shadow-[0_4px_20px_rgba(16,185,129,0.15)]"
                          style={{
                            height: "auto",
                            display: "inline-flex",
                            alignItems: "center",
                            gap: 10,
                            padding: "10px 20px",
                            borderRadius: 12,
                            fontWeight: 700,
                            fontSize: 13,
                            color: "#ffffff",
                            border: "1px solid rgba(255, 255, 255, 0.12)",
                            background: "rgba(255, 255, 255, 0.03)",
                            boxShadow: "0 4px 16px rgba(0, 0, 0, 0.25)",
                          }}
                        >
                          Export danh sách VĐV (.txt)
                        </QButton>

                        {/* Input file ẩn bên ngoài */}
                        <input
                          type="file"
                          ref={fileInputRef}
                          accept=".txt"
                          onChange={handleImportTxt}
                          className="hidden"
                        />

                        {/* QButton kích hoạt chọn file */}
                        <QButton
                          onClick={() => fileInputRef.current?.click()}
                          size="large"
                          icon={
                            <Upload
                              size={16}
                              className="!text-white stroke-[2.5]"
                            />
                          }
                          style={{
                            height: "auto",
                            display: "inline-flex",
                            alignItems: "center",
                            justifyContent: "center",
                            gap: 10,
                            padding: "10px 20px",
                            borderRadius: 12,
                            fontWeight: 700,
                            fontSize: 13,
                            color: "white",
                            border: "1px solid #6ee7b7",
                            background:
                              "linear-gradient(135deg, #10b981, #059669)",
                            boxShadow: "0 4px 20px rgba(16, 185, 129, 0.4)",
                            cursor: "pointer",
                            transition: "all 0.2s ease-in-out",
                          }}
                        >
                          Import kết quả (.txt)
                        </QButton>
                      </div>
                    </div>
                  ),
                },
              ]}
            />
          </div>

          {/* 3. BẢNG HIỂN THỊ DANH SÁCH TRẬN */}
          <div className="flex flex-col gap-3 pt-2">
            <div className="flex items-center justify-between">
              <h4 className="text-sm font-semibold text-slate-200 m-0">
                Danh sách trận ({createdMatches.length})
              </h4>

              <div className="flex items-center gap-2">
                <Input
                  size="large"
                  placeholder="Tìm cơ thủ / số trận..."
                  prefix={<Search size={14} className="text-slate-500" />}
                  value={searchText}
                  onChange={(e) => setSearchText(e.target.value)}
                  className="w-48"
                />

                {createdMatches.length > 0 && (
                  <Popconfirm
                    title="Xác nhận"
                    description="Xóa tất cả trận đã tạo?"
                    onConfirm={() => setCreatedMatches([])}
                    okText="Xóa"
                    cancelText="Hủy"
                    okButtonProps={{
                      size: "middle",
                    }}
                    cancelButtonProps={{
                      size: "middle",
                    }}
                    styles={{
                      container: {
                        padding: "18px 24px",
                      },
                    }}
                    placement="bottomRight"
                  >
                    <QButton
                      size="large"
                      type="text"
                      danger
                      icon={<RotateCcw size={12} />}
                    >
                      Clear
                    </QButton>
                  </Popconfirm>
                )}
              </div>
            </div>

            <Table
              columns={columns}
              dataSource={filteredMatches}
              rowKey="id"
              size="small"
              pagination={{
                size: "middle",
                pageSize: 10,
                showSizeChanger: true,
                pageSizeOptions: ["10", "25", "50"],
                showTotal: (total) => `Tổng ${total} trận`,
              }}
              className="border border-slate-800 rounded-lg overflow-hidden"
            />
          </div>
        </div>
      </Drawer>
    </AntdThemeConfig>
  );
};
