// @generated by protoc-gen-es v2.6.2 with parameter "target=ts"
// @generated from file user/v1/user_service.proto (package user.v1, syntax proto3)
/* eslint-disable */
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import { file_google_protobuf_timestamp, file_google_protobuf_wrappers } from "@bufbuild/protobuf/wkt";
import { file_user_v1_user } from "./user_pb";
/**
 * Describes the file user/v1/user_service.proto.
 */
export const file_user_v1_user_service = /*@__PURE__*/ fileDesc("Chp1c2VyL3YxL3VzZXJfc2VydmljZS5wcm90bxIHdXNlci52MSI9ChJHZXRVc2VyQnlJRFJlcXVlc3QSJwoCaWQYASABKAsyGy5nb29nbGUucHJvdG9idWYuSW50MzJWYWx1ZSIyChNHZXRVc2VyQnlJRFJlc3BvbnNlEhsKBHVzZXIYASABKAsyDS51c2VyLnYxLlVzZXIiQgoUR2V0VXNlckJ5TmFtZVJlcXVlc3QSKgoEbmFtZRgBIAEoCzIcLmdvb2dsZS5wcm90b2J1Zi5TdHJpbmdWYWx1ZSI0ChVHZXRVc2VyQnlOYW1lUmVzcG9uc2USGwoEdXNlchgBIAEoCzINLnVzZXIudjEuVXNlcjKnAQoLVXNlclNlcnZpY2USSAoLR2V0VXNlckJ5SUQSGy51c2VyLnYxLkdldFVzZXJCeUlEUmVxdWVzdBocLnVzZXIudjEuR2V0VXNlckJ5SURSZXNwb25zZRJOCg1HZXRVc2VyQnlOYW1lEh0udXNlci52MS5HZXRVc2VyQnlOYW1lUmVxdWVzdBoeLnVzZXIudjEuR2V0VXNlckJ5TmFtZVJlc3BvbnNlQiVaI2JhY2tlbmQvaW50ZXJuYWwvZ2VuL3VzZXIvdjE7dXNlcnBiYgZwcm90bzM", [file_google_protobuf_timestamp, file_google_protobuf_wrappers, file_user_v1_user]);
/**
 * Describes the message user.v1.GetUserByIDRequest.
 * Use `create(GetUserByIDRequestSchema)` to create a new message.
 */
export const GetUserByIDRequestSchema = /*@__PURE__*/ messageDesc(file_user_v1_user_service, 0);
/**
 * Describes the message user.v1.GetUserByIDResponse.
 * Use `create(GetUserByIDResponseSchema)` to create a new message.
 */
export const GetUserByIDResponseSchema = /*@__PURE__*/ messageDesc(file_user_v1_user_service, 1);
/**
 * Describes the message user.v1.GetUserByNameRequest.
 * Use `create(GetUserByNameRequestSchema)` to create a new message.
 */
export const GetUserByNameRequestSchema = /*@__PURE__*/ messageDesc(file_user_v1_user_service, 2);
/**
 * Describes the message user.v1.GetUserByNameResponse.
 * Use `create(GetUserByNameResponseSchema)` to create a new message.
 */
export const GetUserByNameResponseSchema = /*@__PURE__*/ messageDesc(file_user_v1_user_service, 3);
/**
 * @generated from service user.v1.UserService
 */
export const UserService = /*@__PURE__*/ serviceDesc(file_user_v1_user_service, 0);
