// @generated by protoc-gen-es v2.6.2 with parameter "target=ts"
// @generated from file user/v1/user.proto (package user.v1, syntax proto3)
/* eslint-disable */
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_google_protobuf_timestamp, file_google_protobuf_wrappers } from "@bufbuild/protobuf/wkt";
/**
 * Describes the file user/v1/user.proto.
 */
export const file_user_v1_user = /*@__PURE__*/ fileDesc("ChJ1c2VyL3YxL3VzZXIucHJvdG8SB3VzZXIudjEivgEKBFVzZXISKAoCaWQYASABKAsyHC5nb29nbGUucHJvdG9idWYuU3RyaW5nVmFsdWUSKgoEbmFtZRgCIAEoCzIcLmdvb2dsZS5wcm90b2J1Zi5TdHJpbmdWYWx1ZRIuCgpjcmVhdGVkX2F0GAMgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcBIwCgpzZWNyZXRfa2V5GAQgASgLMhwuZ29vZ2xlLnByb3RvYnVmLlN0cmluZ1ZhbHVlQiVaI2JhY2tlbmQvaW50ZXJuYWwvZ2VuL3VzZXIvdjE7dXNlcnBiYgZwcm90bzM", [file_google_protobuf_timestamp, file_google_protobuf_wrappers]);
/**
 * Describes the message user.v1.User.
 * Use `create(UserSchema)` to create a new message.
 */
export const UserSchema = /*@__PURE__*/ messageDesc(file_user_v1_user, 0);
