// @generated by protoc-gen-es v2.6.2 with parameter "target=ts,import_extension=none"
// @generated from file user/v1/user_service.proto (package user.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import { file_google_protobuf_timestamp, file_google_protobuf_wrappers } from "@bufbuild/protobuf/wkt";
import type { User } from "./user_pb";
import { file_user_v1_user } from "./user_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file user/v1/user_service.proto.
 */
export const file_user_v1_user_service: GenFile = /*@__PURE__*/
  fileDesc("Chp1c2VyL3YxL3VzZXJfc2VydmljZS5wcm90bxIHdXNlci52MSI9ChJHZXRVc2VyQnlJRFJlcXVlc3QSJwoCaWQYASABKAsyGy5nb29nbGUucHJvdG9idWYuSW50MzJWYWx1ZSIyChNHZXRVc2VyQnlJRFJlc3BvbnNlEhsKBHVzZXIYASABKAsyDS51c2VyLnYxLlVzZXIiQgoUR2V0VXNlckJ5TmFtZVJlcXVlc3QSKgoEbmFtZRgBIAEoCzIcLmdvb2dsZS5wcm90b2J1Zi5TdHJpbmdWYWx1ZSI0ChVHZXRVc2VyQnlOYW1lUmVzcG9uc2USGwoEdXNlchgBIAEoCzINLnVzZXIudjEuVXNlcjKnAQoLVXNlclNlcnZpY2USSAoLR2V0VXNlckJ5SUQSGy51c2VyLnYxLkdldFVzZXJCeUlEUmVxdWVzdBocLnVzZXIudjEuR2V0VXNlckJ5SURSZXNwb25zZRJOCg1HZXRVc2VyQnlOYW1lEh0udXNlci52MS5HZXRVc2VyQnlOYW1lUmVxdWVzdBoeLnVzZXIudjEuR2V0VXNlckJ5TmFtZVJlc3BvbnNlQiVaI2JhY2tlbmQvaW50ZXJuYWwvZ2VuL3VzZXIvdjE7dXNlcnBiYgZwcm90bzM", [file_google_protobuf_timestamp, file_google_protobuf_wrappers, file_user_v1_user]);

/**
 * @generated from message user.v1.GetUserByIDRequest
 */
export type GetUserByIDRequest = Message<"user.v1.GetUserByIDRequest"> & {
  /**
   * @generated from field: google.protobuf.Int32Value id = 1;
   */
  id?: number;
};

/**
 * Describes the message user.v1.GetUserByIDRequest.
 * Use `create(GetUserByIDRequestSchema)` to create a new message.
 */
export const GetUserByIDRequestSchema: GenMessage<GetUserByIDRequest> = /*@__PURE__*/
  messageDesc(file_user_v1_user_service, 0);

/**
 * @generated from message user.v1.GetUserByIDResponse
 */
export type GetUserByIDResponse = Message<"user.v1.GetUserByIDResponse"> & {
  /**
   * @generated from field: user.v1.User user = 1;
   */
  user?: User;
};

/**
 * Describes the message user.v1.GetUserByIDResponse.
 * Use `create(GetUserByIDResponseSchema)` to create a new message.
 */
export const GetUserByIDResponseSchema: GenMessage<GetUserByIDResponse> = /*@__PURE__*/
  messageDesc(file_user_v1_user_service, 1);

/**
 * @generated from message user.v1.GetUserByNameRequest
 */
export type GetUserByNameRequest = Message<"user.v1.GetUserByNameRequest"> & {
  /**
   * @generated from field: google.protobuf.StringValue name = 1;
   */
  name?: string;
};

/**
 * Describes the message user.v1.GetUserByNameRequest.
 * Use `create(GetUserByNameRequestSchema)` to create a new message.
 */
export const GetUserByNameRequestSchema: GenMessage<GetUserByNameRequest> = /*@__PURE__*/
  messageDesc(file_user_v1_user_service, 2);

/**
 * @generated from message user.v1.GetUserByNameResponse
 */
export type GetUserByNameResponse = Message<"user.v1.GetUserByNameResponse"> & {
  /**
   * @generated from field: user.v1.User user = 1;
   */
  user?: User;
};

/**
 * Describes the message user.v1.GetUserByNameResponse.
 * Use `create(GetUserByNameResponseSchema)` to create a new message.
 */
export const GetUserByNameResponseSchema: GenMessage<GetUserByNameResponse> = /*@__PURE__*/
  messageDesc(file_user_v1_user_service, 3);

/**
 * @generated from service user.v1.UserService
 */
export const UserService: GenService<{
  /**
   * @generated from rpc user.v1.UserService.GetUserByID
   */
  getUserByID: {
    methodKind: "unary";
    input: typeof GetUserByIDRequestSchema;
    output: typeof GetUserByIDResponseSchema;
  },
  /**
   * @generated from rpc user.v1.UserService.GetUserByName
   */
  getUserByName: {
    methodKind: "unary";
    input: typeof GetUserByNameRequestSchema;
    output: typeof GetUserByNameResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_user_v1_user_service, 0);

