// @generated by protoc-gen-es v2.6.2 with parameter "target=ts,import_extension=none"
// @generated from file tournament/v1/tournament_service.proto (package tournament.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { Tournament } from "./tournament_pb";
import { file_tournament_v1_tournament } from "./tournament_pb";
import type { Empty } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_empty } from "@bufbuild/protobuf/wkt";
import { file_buf_validate_validate } from "../../buf/validate/validate_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file tournament/v1/tournament_service.proto.
 */
export const file_tournament_v1_tournament_service: GenFile = /*@__PURE__*/
  fileDesc("CiZ0b3VybmFtZW50L3YxL3RvdXJuYW1lbnRfc2VydmljZS5wcm90bxINdG91cm5hbWVudC52MSKBAgoVR2V0VG91cm5hbWVudHNSZXF1ZXN0EhUKBHBhZ2UYASABKAVCB7pIBBoCIAASFgoFbGltaXQYAiABKAVCB7pIBBoCIAASZgoGZmlsdGVyGAMgASgJQla6SFO6AVAKGWZpbHRlcl9yZXF1aXJlc19maWx0ZXJfYnkaM2hhcyh0aGlzLmZpbHRlcl9ieSkgPyB0aGlzLmZpbHRlci5zaXplKCkgPiAwIDogdHJ1ZRIRCglmaWx0ZXJfYnkYBCABKAkSGQoRZmlsdGVyX21hdGNoX3R5cGUYBSABKAkSDwoHc29ydF9ieRgGIAEoCRISCgpzb3J0X29yZGVyGAcgASgJIkgKFkdldFRvdXJuYW1lbnRzUmVzcG9uc2USLgoLdG91cm5hbWVudHMYASADKAsyGS50b3VybmFtZW50LnYxLlRvdXJuYW1lbnQiigEKHEdldFRvdXJuYW1lbnRzUmVxdWVzdFdyYXBwZXISJwoFZW1wdHkYASABKAsyFi5nb29nbGUucHJvdG9idWYuRW1wdHlIABI2CgZmaWx0ZXIYAiABKAsyJC50b3VybmFtZW50LnYxLkdldFRvdXJuYW1lbnRzUmVxdWVzdEgAQgkKB3JlcXVlc3QiJwoXQ3JlYXRlVG91cm5hbWVudFJlcXVlc3QSDAoEbmFtZRgBIAEoCSImChhDcmVhdGVUb3VybmFtZW50UmVzcG9uc2USCgoCaWQYASABKAky3gEKEVRvdXJuYW1lbnRTZXJ2aWNlEmQKDkdldFRvdXJuYW1lbnRzEisudG91cm5hbWVudC52MS5HZXRUb3VybmFtZW50c1JlcXVlc3RXcmFwcGVyGiUudG91cm5hbWVudC52MS5HZXRUb3VybmFtZW50c1Jlc3BvbnNlEmMKEENyZWF0ZVRvdXJuYW1lbnQSJi50b3VybmFtZW50LnYxLkNyZWF0ZVRvdXJuYW1lbnRSZXF1ZXN0GicudG91cm5hbWVudC52MS5DcmVhdGVUb3VybmFtZW50UmVzcG9uc2VCMVovYmFja2VuZC9pbnRlcm5hbC9nZW4vdG91cm5hbWVudC92MTt0b3VybmFtZW50cGJiBnByb3RvMw", [file_tournament_v1_tournament, file_google_protobuf_empty, file_buf_validate_validate]);

/**
 * Request for listing tournaments with pagination, filtering, and sorting.
 *
 * @generated from message tournament.v1.GetTournamentsRequest
 */
export type GetTournamentsRequest = Message<"tournament.v1.GetTournamentsRequest"> & {
  /**
   * Page number (1-based)
   *
   * @generated from field: int32 page = 1;
   */
  page: number;

  /**
   * Page size
   *
   * @generated from field: int32 limit = 2;
   */
  limit: number;

  /**
   * Filter value
   *
   * @generated from field: string filter = 3;
   */
  filter: string;

  /**
   * Field name to filter on
   *
   * @generated from field: string filter_by = 4;
   */
  filterBy: string;

  /**
   * Match type (contains, equals, etc.)
   *
   * @generated from field: string filter_match_type = 5;
   */
  filterMatchType: string;

  /**
   * Field name to sort by
   *
   * @generated from field: string sort_by = 6;
   */
  sortBy: string;

  /**
   * Sort order (asc or desc)
   *
   * @generated from field: string sort_order = 7;
   */
  sortOrder: string;
};

/**
 * Describes the message tournament.v1.GetTournamentsRequest.
 * Use `create(GetTournamentsRequestSchema)` to create a new message.
 */
export const GetTournamentsRequestSchema: GenMessage<GetTournamentsRequest> = /*@__PURE__*/
  messageDesc(file_tournament_v1_tournament_service, 0);

/**
 * Response containing a list of tournaments.
 *
 * @generated from message tournament.v1.GetTournamentsResponse
 */
export type GetTournamentsResponse = Message<"tournament.v1.GetTournamentsResponse"> & {
  /**
   * Tournament list
   *
   * @generated from field: repeated tournament.v1.Tournament tournaments = 1;
   */
  tournaments: Tournament[];
};

/**
 * Describes the message tournament.v1.GetTournamentsResponse.
 * Use `create(GetTournamentsResponseSchema)` to create a new message.
 */
export const GetTournamentsResponseSchema: GenMessage<GetTournamentsResponse> = /*@__PURE__*/
  messageDesc(file_tournament_v1_tournament_service, 1);

/**
 * Wrapper allowing empty request or filtered request.
 *
 * @generated from message tournament.v1.GetTournamentsRequestWrapper
 */
export type GetTournamentsRequestWrapper = Message<"tournament.v1.GetTournamentsRequestWrapper"> & {
  /**
   * @generated from oneof tournament.v1.GetTournamentsRequestWrapper.request
   */
  request: {
    /**
     * Fetch all tournaments with defaults
     *
     * @generated from field: google.protobuf.Empty empty = 1;
     */
    value: Empty;
    case: "empty";
  } | {
    /**
     * Fetch tournaments with filters
     *
     * @generated from field: tournament.v1.GetTournamentsRequest filter = 2;
     */
    value: GetTournamentsRequest;
    case: "filter";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message tournament.v1.GetTournamentsRequestWrapper.
 * Use `create(GetTournamentsRequestWrapperSchema)` to create a new message.
 */
export const GetTournamentsRequestWrapperSchema: GenMessage<GetTournamentsRequestWrapper> = /*@__PURE__*/
  messageDesc(file_tournament_v1_tournament_service, 2);

/**
 * Request for creating a new tournament.
 *
 * @generated from message tournament.v1.CreateTournamentRequest
 */
export type CreateTournamentRequest = Message<"tournament.v1.CreateTournamentRequest"> & {
  /**
   * Tournament name
   *
   * @generated from field: string name = 1;
   */
  name: string;
};

/**
 * Describes the message tournament.v1.CreateTournamentRequest.
 * Use `create(CreateTournamentRequestSchema)` to create a new message.
 */
export const CreateTournamentRequestSchema: GenMessage<CreateTournamentRequest> = /*@__PURE__*/
  messageDesc(file_tournament_v1_tournament_service, 3);

/**
 * Response after creating a tournament.
 *
 * @generated from message tournament.v1.CreateTournamentResponse
 */
export type CreateTournamentResponse = Message<"tournament.v1.CreateTournamentResponse"> & {
  /**
   * Created tournament ID
   *
   * @generated from field: string id = 1;
   */
  id: string;
};

/**
 * Describes the message tournament.v1.CreateTournamentResponse.
 * Use `create(CreateTournamentResponseSchema)` to create a new message.
 */
export const CreateTournamentResponseSchema: GenMessage<CreateTournamentResponse> = /*@__PURE__*/
  messageDesc(file_tournament_v1_tournament_service, 4);

/**
 * Tournament service definition.
 *
 * @generated from service tournament.v1.TournamentService
 */
export const TournamentService: GenService<{
  /**
   * Returns a paginated list of tournaments.
   *
   * @generated from rpc tournament.v1.TournamentService.GetTournaments
   */
  getTournaments: {
    methodKind: "unary";
    input: typeof GetTournamentsRequestWrapperSchema;
    output: typeof GetTournamentsResponseSchema;
  },
  /**
   * Creates a new tournament.
   *
   * @generated from rpc tournament.v1.TournamentService.CreateTournament
   */
  createTournament: {
    methodKind: "unary";
    input: typeof CreateTournamentRequestSchema;
    output: typeof CreateTournamentResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_tournament_v1_tournament_service, 0);

