// @generated by protoc-gen-es v2.6.2 with parameter "target=ts,import_extension=none"
// @generated from file tournament/v1/tournament.proto (package tournament.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_google_protobuf_timestamp, file_google_protobuf_wrappers } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file tournament/v1/tournament.proto.
 */
export const file_tournament_v1_tournament: GenFile = /*@__PURE__*/
  fileDesc("Ch50b3VybmFtZW50L3YxL3RvdXJuYW1lbnQucHJvdG8SDXRvdXJuYW1lbnQudjEiIgoGUGxheWVyEgoKAmlkGAEgASgJEgwKBG5hbWUYAiABKAkiggYKClRvdXJuYW1lbnQSCgoCaWQYASABKAkSDAoEbmFtZRgCIAEoCRIrCgR0eXBlGAMgASgOMh0udG91cm5hbWVudC52MS5Ub3VybmFtZW50VHlwZRIvCgZmb3JtYXQYBCABKA4yHy50b3VybmFtZW50LnYxLlRvdXJuYW1lbnRGb3JtYXQSOAoSZm9ybWF0X2Rlc2NyaXB0aW9uGAUgASgLMhwuZ29vZ2xlLnByb3RvYnVmLlN0cmluZ1ZhbHVlEjAKCnN0YXJ0X2RhdGUYBiABKAsyHC5nb29nbGUucHJvdG9idWYuU3RyaW5nVmFsdWUSLgoIZW5kX2RhdGUYByABKAsyHC5nb29nbGUucHJvdG9idWYuU3RyaW5nVmFsdWUSLgoIbG9jYXRpb24YCCABKAsyHC5nb29nbGUucHJvdG9idWYuU3RyaW5nVmFsdWUSKwoGdGFibGVzGAkgASgLMhsuZ29vZ2xlLnByb3RvYnVmLkludDMyVmFsdWUSMQoLdG90YWxfcHJpemUYCiABKAsyHC5nb29nbGUucHJvdG9idWYuU3RyaW5nVmFsdWUSLwoJZW50cnlfZmVlGAsgASgLMhwuZ29vZ2xlLnByb3RvYnVmLlN0cmluZ1ZhbHVlEjAKC21heF9wbGF5ZXJzGAwgASgLMhsuZ29vZ2xlLnByb3RvYnVmLkludDMyVmFsdWUSLwoGc3RhdHVzGA0gASgOMh8udG91cm5hbWVudC52MS5Ub3VybmFtZW50U3RhdHVzEi8KCW9yZ2FuaXplchgOIAEoCzIcLmdvb2dsZS5wcm90b2J1Zi5TdHJpbmdWYWx1ZRISCgpjcmVhdGVkX2F0GA8gASgJEhEKCXVwZGF0ZV9hdBgQIAEoCRIxCgtkZXNjcmlwdGlvbhgRIAEoCzIcLmdvb2dsZS5wcm90b2J1Zi5TdHJpbmdWYWx1ZRIxChJyZWdpc3RlcmVkX3BsYXllcnMYEiADKAsyFS50b3VybmFtZW50LnYxLlBsYXllciqCAgoQVG91cm5hbWVudFN0YXR1cxIhCh1UT1VSTkFNRU5UX1NUQVRVU19VTlNQRUNJRklFRBAAEiEKHVRPVVJOQU1FTlRfU1RBVFVTX1JFR0lTVEVSSU5HEAESKQolVE9VUk5BTUVOVF9TVEFUVVNfUkVHSVNUUkFUSU9OX0NMT1NFRBACEh0KGVRPVVJOQU1FTlRfU1RBVFVTX1NUQVJURUQQAxIdChlUT1VSTkFNRU5UX1NUQVRVU19SVU5OSU5HEAQSHgoaVE9VUk5BTUVOVF9TVEFUVVNfRklOSVNIRUQQBRIfChtUT1VSTkFNRU5UX1NUQVRVU19DQU5DRUxMRUQQBipGCg5Ub3VybmFtZW50VHlwZRIaChZUT1VSTkFNRU5UX1RZUEVfU0lOR0xFEAASGAoUVE9VUk5BTUVOVF9UWVBFX1RFQU0QASpnChBUb3VybmFtZW50Rm9ybWF0EhoKFlRPVVJOQU1FTlRfVFlQRV84X0JBTEwQABIaChZUT1VSTkFNRU5UX1RZUEVfOV9CQUxMEAESGwoXVE9VUk5BTUVOVF9UWVBFXzEwX0JBTEwQAkIxWi9iYWNrZW5kL2ludGVybmFsL2dlbi90b3VybmFtZW50L3YxO3RvdXJuYW1lbnRwYmIGcHJvdG8z", [file_google_protobuf_timestamp, file_google_protobuf_wrappers]);

/**
 * @generated from message tournament.v1.Player
 */
export type Player = Message<"tournament.v1.Player"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string name = 2;
   */
  name: string;
};

/**
 * Describes the message tournament.v1.Player.
 * Use `create(PlayerSchema)` to create a new message.
 */
export const PlayerSchema: GenMessage<Player> = /*@__PURE__*/
  messageDesc(file_tournament_v1_tournament, 0);

/**
 * Thông tin giải đấu
 *
 * @generated from message tournament.v1.Tournament
 */
export type Tournament = Message<"tournament.v1.Tournament"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * @generated from field: tournament.v1.TournamentType type = 3;
   */
  type: TournamentType;

  /**
   * @generated from field: tournament.v1.TournamentFormat format = 4;
   */
  format: TournamentFormat;

  /**
   * @generated from field: google.protobuf.StringValue format_description = 5;
   */
  formatDescription?: string;

  /**
   * @generated from field: google.protobuf.StringValue start_date = 6;
   */
  startDate?: string;

  /**
   * @generated from field: google.protobuf.StringValue end_date = 7;
   */
  endDate?: string;

  /**
   * @generated from field: google.protobuf.StringValue location = 8;
   */
  location?: string;

  /**
   * @generated from field: google.protobuf.Int32Value tables = 9;
   */
  tables?: number;

  /**
   * @generated from field: google.protobuf.StringValue total_prize = 10;
   */
  totalPrize?: string;

  /**
   * @generated from field: google.protobuf.StringValue entry_fee = 11;
   */
  entryFee?: string;

  /**
   * @generated from field: google.protobuf.Int32Value max_players = 12;
   */
  maxPlayers?: number;

  /**
   * @generated from field: tournament.v1.TournamentStatus status = 13;
   */
  status: TournamentStatus;

  /**
   * @generated from field: google.protobuf.StringValue organizer = 14;
   */
  organizer?: string;

  /**
   * @generated from field: string created_at = 15;
   */
  createdAt: string;

  /**
   * @generated from field: string update_at = 16;
   */
  updateAt: string;

  /**
   * @generated from field: google.protobuf.StringValue description = 17;
   */
  description?: string;

  /**
   * @generated from field: repeated tournament.v1.Player registered_players = 18;
   */
  registeredPlayers: Player[];
};

/**
 * Describes the message tournament.v1.Tournament.
 * Use `create(TournamentSchema)` to create a new message.
 */
export const TournamentSchema: GenMessage<Tournament> = /*@__PURE__*/
  messageDesc(file_tournament_v1_tournament, 1);

/**
 * Trạng thái giải đấu
 *
 * @generated from enum tournament.v1.TournamentStatus
 */
export enum TournamentStatus {
  /**
   * @generated from enum value: TOURNAMENT_STATUS_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: TOURNAMENT_STATUS_REGISTERING = 1;
   */
  REGISTERING = 1,

  /**
   * @generated from enum value: TOURNAMENT_STATUS_REGISTRATION_CLOSED = 2;
   */
  REGISTRATION_CLOSED = 2,

  /**
   * @generated from enum value: TOURNAMENT_STATUS_STARTED = 3;
   */
  STARTED = 3,

  /**
   * @generated from enum value: TOURNAMENT_STATUS_RUNNING = 4;
   */
  RUNNING = 4,

  /**
   * @generated from enum value: TOURNAMENT_STATUS_FINISHED = 5;
   */
  FINISHED = 5,

  /**
   * @generated from enum value: TOURNAMENT_STATUS_CANCELLED = 6;
   */
  CANCELLED = 6,
}

/**
 * Describes the enum tournament.v1.TournamentStatus.
 */
export const TournamentStatusSchema: GenEnum<TournamentStatus> = /*@__PURE__*/
  enumDesc(file_tournament_v1_tournament, 0);

/**
 * @generated from enum tournament.v1.TournamentType
 */
export enum TournamentType {
  /**
   * @generated from enum value: TOURNAMENT_TYPE_SINGLE = 0;
   */
  SINGLE = 0,

  /**
   * @generated from enum value: TOURNAMENT_TYPE_TEAM = 1;
   */
  TEAM = 1,
}

/**
 * Describes the enum tournament.v1.TournamentType.
 */
export const TournamentTypeSchema: GenEnum<TournamentType> = /*@__PURE__*/
  enumDesc(file_tournament_v1_tournament, 1);

/**
 * @generated from enum tournament.v1.TournamentFormat
 */
export enum TournamentFormat {
  /**
   * @generated from enum value: TOURNAMENT_TYPE_8_BALL = 0;
   */
  TOURNAMENT_TYPE_8_BALL = 0,

  /**
   * @generated from enum value: TOURNAMENT_TYPE_9_BALL = 1;
   */
  TOURNAMENT_TYPE_9_BALL = 1,

  /**
   * @generated from enum value: TOURNAMENT_TYPE_10_BALL = 2;
   */
  TOURNAMENT_TYPE_10_BALL = 2,
}

/**
 * Describes the enum tournament.v1.TournamentFormat.
 */
export const TournamentFormatSchema: GenEnum<TournamentFormat> = /*@__PURE__*/
  enumDesc(file_tournament_v1_tournament, 2);

