// @generated by protoc-gen-es v2.12.1 with parameter "target=ts,import_extension=none"
// @generated from file tournament/v1/tournament_error.proto (package tournament.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { AppError } from "../../common/v1/errors_pb";
import { file_common_v1_errors } from "../../common/v1/errors_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file tournament/v1/tournament_error.proto.
 */
export const file_tournament_v1_tournament_error: GenFile = /*@__PURE__*/
  fileDesc("CiR0b3VybmFtZW50L3YxL3RvdXJuYW1lbnRfZXJyb3IucHJvdG8SDXRvdXJuYW1lbnQudjEiagoPVG91cm5hbWVudEVycm9yEiUKCEFwcEVycm9yGAEgASgLMhMuY29tbW9uLnYxLkFwcEVycm9yEjAKBGNvZGUYAiABKA4yIi50b3VybmFtZW50LnYxLlRvdXJuYW1lbnRFcnJvckNvZGUqoQEKE1RvdXJuYW1lbnRFcnJvckNvZGUSDwoLVU5TUEVDSUZJRUQQABIRCg1OQU1FX1JFUVVJUkVEEAESEgoOVkVOVUVfUkVRVUlSRUQQAhITCg9ST1VORFNfUkVRVUlSRUQQAxINCglOT1RfRk9VTkQQBBIaChZST1VORFNfQ09ORklHX1JFUVVJUkVEEAUSEgoOSU5URVJOQUxfRVJST1IQBkIxWi9iYWNrZW5kL2ludGVybmFsL2dlbi90b3VybmFtZW50L3YxO3RvdXJuYW1lbnRwYmIGcHJvdG8z", [file_common_v1_errors]);

/**
 * @generated from message tournament.v1.TournamentError
 */
export type TournamentError = Message<"tournament.v1.TournamentError"> & {
  /**
   * @generated from field: common.v1.AppError AppError = 1;
   */
  AppError?: AppError | undefined;

  /**
   * @generated from field: tournament.v1.TournamentErrorCode code = 2;
   */
  code: TournamentErrorCode;
};

/**
 * Describes the message tournament.v1.TournamentError.
 * Use `create(TournamentErrorSchema)` to create a new message.
 */
export const TournamentErrorSchema: GenMessage<TournamentError> = /*@__PURE__*/
  messageDesc(file_tournament_v1_tournament_error, 0);

/**
 * @generated from enum tournament.v1.TournamentErrorCode
 */
export enum TournamentErrorCode {
  /**
   * @generated from enum value: UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: NAME_REQUIRED = 1;
   */
  NAME_REQUIRED = 1,

  /**
   * @generated from enum value: VENUE_REQUIRED = 2;
   */
  VENUE_REQUIRED = 2,

  /**
   * @generated from enum value: ROUNDS_REQUIRED = 3;
   */
  ROUNDS_REQUIRED = 3,

  /**
   * @generated from enum value: NOT_FOUND = 4;
   */
  NOT_FOUND = 4,

  /**
   * @generated from enum value: ROUNDS_CONFIG_REQUIRED = 5;
   */
  ROUNDS_CONFIG_REQUIRED = 5,

  /**
   * @generated from enum value: INTERNAL_ERROR = 6;
   */
  INTERNAL_ERROR = 6,
}

/**
 * Describes the enum tournament.v1.TournamentErrorCode.
 */
export const TournamentErrorCodeSchema: GenEnum<TournamentErrorCode> = /*@__PURE__*/
  enumDesc(file_tournament_v1_tournament_error, 0);

