// @generated by protoc-gen-es v2.12.1 with parameter "target=ts,import_extension=none"
// @generated from file common/v1/common.proto (package common.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file common/v1/common.proto.
 */
export const file_common_v1_common: GenFile = /*@__PURE__*/
  fileDesc("ChZjb21tb24vdjEvY29tbW9uLnByb3RvEgljb21tb24udjEiagoPQXV0aEVycm9yRGV0YWlsEiQKBnJlYXNvbhgBIAEoDjIULmNvbW1vbi52MS5BdXRoRXJyb3ISFAoMZm9yY2VfbG9nb3V0GAIgASgIEhsKE3Jldm9rZV9hbGxfc2Vzc2lvbnMYAyABKAgqvQIKCUF1dGhFcnJvchIaChZBVVRIX0VSUk9SX1VOU1BFQ0lGSUVEEAASIwofQVVUSF9FUlJPUl9JTlZBTElEX0FDQ0VTU19UT0tFThABEiQKIEFVVEhfRVJST1JfSU5WQUxJRF9SRUZSRVNIX1RPS0VOEAISIwofQVVUSF9FUlJPUl9SRUZSRVNIX1RPS0VOX1JFVVNFRBADEh4KGkFVVEhfRVJST1JfREVWSUNFX01JU01BVENIEAQSHgoaQVVUSF9FUlJPUl9TRVNTSU9OX0VYUElSRUQQBRIeChpBVVRIX0VSUk9SX1NFU1NJT05fUkVWT0tFRBAGEiIKHkFVVEhfRVJST1JfU09GVF9MT0dJTl9SRVFVSVJFRBAHEiAKHEFVVEhfRVJST1JfU09GVF9MT0dJTl9GQUlMRUQQCCrZAgoTU2Vzc2lvblJldm9rZVJlYXNvbhIlCiFTRVNTSU9OX1JFVk9LRV9SRUFTT05fVU5TUEVDSUZJRUQQABIhCh1TRVNTSU9OX1JFVk9LRV9SRUFTT05fUk9UQVRFRBABEiQKIFNFU1NJT05fUkVWT0tFX1JFQVNPTl9MT0dHRURfT1VUEAISKgomU0VTU0lPTl9SRVZPS0VfUkVBU09OX0ZPUkNFX0xPR0dFRF9PVVQQAxIuCipTRVNTSU9OX1JFVk9LRV9SRUFTT05fVE9LRU5fUkVVU0VfREVURUNURUQQBBIhCh1TRVNTSU9OX1JFVk9LRV9SRUFTT05fRVhQSVJFRBAFEioKJlNFU1NJT05fUkVWT0tFX1JFQVNPTl9QQVNTV09SRF9DSEFOR0VEEAYSJwojU0VTU0lPTl9SRVZPS0VfUkVBU09OX1VTRVJfRElTQUJMRUQQB0IpWidiYWNrZW5kL2ludGVybmFsL2dlbi9jb21tb24vdjE7Y29tbW9ucGJiBnByb3RvMw");

/**
 * @generated from message common.v1.AuthErrorDetail
 */
export type AuthErrorDetail = Message<"common.v1.AuthErrorDetail"> & {
  /**
   * @generated from field: common.v1.AuthError reason = 1;
   */
  reason: AuthError;

  /**
   * @generated from field: bool force_logout = 2;
   */
  forceLogout: boolean;

  /**
   * @generated from field: bool revoke_all_sessions = 3;
   */
  revokeAllSessions: boolean;
};

/**
 * Describes the message common.v1.AuthErrorDetail.
 * Use `create(AuthErrorDetailSchema)` to create a new message.
 */
export const AuthErrorDetailSchema: GenMessage<AuthErrorDetail> = /*@__PURE__*/
  messageDesc(file_common_v1_common, 0);

/**
 * @generated from enum common.v1.AuthError
 */
export enum AuthError {
  /**
   * @generated from enum value: AUTH_ERROR_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: AUTH_ERROR_INVALID_ACCESS_TOKEN = 1;
   */
  INVALID_ACCESS_TOKEN = 1,

  /**
   * @generated from enum value: AUTH_ERROR_INVALID_REFRESH_TOKEN = 2;
   */
  INVALID_REFRESH_TOKEN = 2,

  /**
   * @generated from enum value: AUTH_ERROR_REFRESH_TOKEN_REUSED = 3;
   */
  REFRESH_TOKEN_REUSED = 3,

  /**
   * @generated from enum value: AUTH_ERROR_DEVICE_MISMATCH = 4;
   */
  DEVICE_MISMATCH = 4,

  /**
   * @generated from enum value: AUTH_ERROR_SESSION_EXPIRED = 5;
   */
  SESSION_EXPIRED = 5,

  /**
   * @generated from enum value: AUTH_ERROR_SESSION_REVOKED = 6;
   */
  SESSION_REVOKED = 6,

  /**
   * @generated from enum value: AUTH_ERROR_SOFT_LOGIN_REQUIRED = 7;
   */
  SOFT_LOGIN_REQUIRED = 7,

  /**
   * @generated from enum value: AUTH_ERROR_SOFT_LOGIN_FAILED = 8;
   */
  SOFT_LOGIN_FAILED = 8,
}

/**
 * Describes the enum common.v1.AuthError.
 */
export const AuthErrorSchema: GenEnum<AuthError> = /*@__PURE__*/
  enumDesc(file_common_v1_common, 0);

/**
 * @generated from enum common.v1.SessionRevokeReason
 */
export enum SessionRevokeReason {
  /**
   * @generated from enum value: SESSION_REVOKE_REASON_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: SESSION_REVOKE_REASON_ROTATED = 1;
   */
  ROTATED = 1,

  /**
   * @generated from enum value: SESSION_REVOKE_REASON_LOGGED_OUT = 2;
   */
  LOGGED_OUT = 2,

  /**
   * @generated from enum value: SESSION_REVOKE_REASON_FORCE_LOGGED_OUT = 3;
   */
  FORCE_LOGGED_OUT = 3,

  /**
   * @generated from enum value: SESSION_REVOKE_REASON_TOKEN_REUSE_DETECTED = 4;
   */
  TOKEN_REUSE_DETECTED = 4,

  /**
   * @generated from enum value: SESSION_REVOKE_REASON_EXPIRED = 5;
   */
  EXPIRED = 5,

  /**
   * @generated from enum value: SESSION_REVOKE_REASON_PASSWORD_CHANGED = 6;
   */
  PASSWORD_CHANGED = 6,

  /**
   * @generated from enum value: SESSION_REVOKE_REASON_USER_DISABLED = 7;
   */
  USER_DISABLED = 7,
}

/**
 * Describes the enum common.v1.SessionRevokeReason.
 */
export const SessionRevokeReasonSchema: GenEnum<SessionRevokeReason> = /*@__PURE__*/
  enumDesc(file_common_v1_common, 1);

