// @generated by protoc-gen-es v2.12.1 with parameter "target=ts,import_extension=none"
// @generated from file common/v1/errors.proto (package common.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file common/v1/errors.proto.
 */
export const file_common_v1_errors: GenFile = /*@__PURE__*/
  fileDesc("ChZjb21tb24vdjEvZXJyb3JzLnByb3RvEgljb21tb24udjEiQgoIQXBwRXJyb3ISDwoHbWVzc2FnZRgBIAEoCRIlCghzZXZlcml0eRgCIAEoDjITLmNvbW1vbi52MS5TZXZlcml0eSpRCghTZXZlcml0eRIYChRTRVZFUklUWV9VTlNQRUNJRklFRBAAEhUKEVNFVkVSSVRZX0JMT0NLSU5HEAESFAoQU0VWRVJJVFlfV0FSTklORxACQilaJ2JhY2tlbmQvaW50ZXJuYWwvZ2VuL2NvbW1vbi92MTtjb21tb25wYmIGcHJvdG8z");

/**
 * @generated from message common.v1.AppError
 */
export type AppError = Message<"common.v1.AppError"> & {
  /**
   * @generated from field: string message = 1;
   */
  message: string;

  /**
   * @generated from field: common.v1.Severity severity = 2;
   */
  severity: Severity;
};

/**
 * Describes the message common.v1.AppError.
 * Use `create(AppErrorSchema)` to create a new message.
 */
export const AppErrorSchema: GenMessage<AppError> = /*@__PURE__*/
  messageDesc(file_common_v1_errors, 0);

/**
 * @generated from enum common.v1.Severity
 */
export enum Severity {
  /**
   * @generated from enum value: SEVERITY_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: SEVERITY_BLOCKING = 1;
   */
  BLOCKING = 1,

  /**
   * @generated from enum value: SEVERITY_WARNING = 2;
   */
  WARNING = 2,
}

/**
 * Describes the enum common.v1.Severity.
 */
export const SeveritySchema: GenEnum<Severity> = /*@__PURE__*/
  enumDesc(file_common_v1_errors, 0);

