// @generated by protoc-gen-es v2.11.0 with parameter "target=ts,import_extension=none"
// @generated from file participant/v1/participant.proto (package participant.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file participant/v1/participant.proto.
 */
export const file_participant_v1_participant: GenFile = /*@__PURE__*/
  fileDesc("CiBwYXJ0aWNpcGFudC92MS9wYXJ0aWNpcGFudC5wcm90bxIOcGFydGljaXBhbnQudjEiXgoLUGFydGljaXBhbnQSCgoCaWQYASABKAkSFAoMZGlzcGxheV9uYW1lGAIgASgJEhAKCG1hdGNoX2lkGAMgASgJEgwKBHNsb3QYBCABKAUSDQoFc2NvcmUYBSABKAVCM1oxYmFja2VuZC9pbnRlcm5hbC9nZW4vcGFydGljaXBhbnQvdjE7cGFydGljaXBhbnRwYmIGcHJvdG8z");

/**
 * @generated from message participant.v1.Participant
 */
export type Participant = Message<"participant.v1.Participant"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string display_name = 2;
   */
  displayName: string;

  /**
   * @generated from field: string match_id = 3;
   */
  matchId: string;

  /**
   * @generated from field: int32 slot = 4;
   */
  slot: number;

  /**
   * @generated from field: int32 score = 5;
   */
  score: number;
};

/**
 * Describes the message participant.v1.Participant.
 * Use `create(ParticipantSchema)` to create a new message.
 */
export const ParticipantSchema: GenMessage<Participant> = /*@__PURE__*/
  messageDesc(file_participant_v1_participant, 0);

