// @generated by protoc-gen-es v2.12.1 with parameter "target=ts,import_extension=none"
// @generated from file participant/v1/participant.proto (package participant.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file participant/v1/participant.proto.
 */
export const file_participant_v1_participant: GenFile = /*@__PURE__*/
  fileDesc("CiBwYXJ0aWNpcGFudC92MS9wYXJ0aWNpcGFudC5wcm90bxIOcGFydGljaXBhbnQudjEiXgoLUGFydGljaXBhbnQSCgoCaWQYASABKAkSFAoMZGlzcGxheV9uYW1lGAIgASgJEhAKCG1hdGNoX2lkGAMgASgJEgwKBHNsb3QYBCABKAUSDQoFc2NvcmUYBSABKAUicgoVVG91cm5hbWVudFBhcnRpY2lwYW50EgoKAmlkGAEgASgJEhEKCXBsYXllcl9pZBgCIAEoCRIUCgxkaXNwbGF5X25hbWUYAyABKAkSEwoLbmF0aW9uYWxpdHkYBCABKAkSDwoHcmFua2luZxgFIAEoCUIzWjFiYWNrZW5kL2ludGVybmFsL2dlbi9wYXJ0aWNpcGFudC92MTtwYXJ0aWNpcGFudHBiYgZwcm90bzM");

/**
 * @generated from message participant.v1.Participant
 */
export type Participant = Message<"participant.v1.Participant"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string display_name = 2;
   */
  displayName: string;

  /**
   * @generated from field: string match_id = 3;
   */
  matchId: string;

  /**
   * @generated from field: int32 slot = 4;
   */
  slot: number;

  /**
   * @generated from field: int32 score = 5;
   */
  score: number;
};

/**
 * Describes the message participant.v1.Participant.
 * Use `create(ParticipantSchema)` to create a new message.
 */
export const ParticipantSchema: GenMessage<Participant> = /*@__PURE__*/
  messageDesc(file_participant_v1_participant, 0);

/**
 * @generated from message participant.v1.TournamentParticipant
 */
export type TournamentParticipant = Message<"participant.v1.TournamentParticipant"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string player_id = 2;
   */
  playerId: string;

  /**
   * @generated from field: string display_name = 3;
   */
  displayName: string;

  /**
   * @generated from field: string nationality = 4;
   */
  nationality: string;

  /**
   * @generated from field: string ranking = 5;
   */
  ranking: string;
};

/**
 * Describes the message participant.v1.TournamentParticipant.
 * Use `create(TournamentParticipantSchema)` to create a new message.
 */
export const TournamentParticipantSchema: GenMessage<TournamentParticipant> = /*@__PURE__*/
  messageDesc(file_participant_v1_participant, 1);

