// @generated by protoc-gen-es v2.12.1 with parameter "target=ts,import_extension=none"
// @generated from file participant/v1/participant_service.proto (package participant.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { Participant } from "./participant_pb";
import { file_participant_v1_participant } from "./participant_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file participant/v1/participant_service.proto.
 */
export const file_participant_v1_participant_service: GenFile = /*@__PURE__*/
  fileDesc("CihwYXJ0aWNpcGFudC92MS9wYXJ0aWNpcGFudF9zZXJ2aWNlLnByb3RvEg5wYXJ0aWNpcGFudC52MSI9CiRHZXRQYXJ0aWNpcGFudHNCeVRvdXJuYW1lbnRJRFJlcXVlc3QSFQoNdG91cm5hbWVudF9pZBgBIAEoCSJaCiVHZXRQYXJ0aWNpcGFudHNCeVRvdXJuYW1lbnRJRFJlc3BvbnNlEjEKDHBhcnRpY2lwYW50cxgBIAMoCzIbLnBhcnRpY2lwYW50LnYxLlBhcnRpY2lwYW50MqMBChJQYXJ0aWNpcGFudFNlcnZpY2USjAEKHUdldFBhcnRpY2lwYW50c0J5VG91cm5hbWVudElEEjQucGFydGljaXBhbnQudjEuR2V0UGFydGljaXBhbnRzQnlUb3VybmFtZW50SURSZXF1ZXN0GjUucGFydGljaXBhbnQudjEuR2V0UGFydGljaXBhbnRzQnlUb3VybmFtZW50SURSZXNwb25zZUIzWjFiYWNrZW5kL2ludGVybmFsL2dlbi9wYXJ0aWNpcGFudC92MTtwYXJ0aWNpcGFudHBiYgZwcm90bzM", [file_participant_v1_participant]);

/**
 * @generated from message participant.v1.GetParticipantsByTournamentIDRequest
 */
export type GetParticipantsByTournamentIDRequest = Message<"participant.v1.GetParticipantsByTournamentIDRequest"> & {
  /**
   * @generated from field: string tournament_id = 1;
   */
  tournamentId: string;
};

/**
 * Describes the message participant.v1.GetParticipantsByTournamentIDRequest.
 * Use `create(GetParticipantsByTournamentIDRequestSchema)` to create a new message.
 */
export const GetParticipantsByTournamentIDRequestSchema: GenMessage<GetParticipantsByTournamentIDRequest> = /*@__PURE__*/
  messageDesc(file_participant_v1_participant_service, 0);

/**
 * @generated from message participant.v1.GetParticipantsByTournamentIDResponse
 */
export type GetParticipantsByTournamentIDResponse = Message<"participant.v1.GetParticipantsByTournamentIDResponse"> & {
  /**
   * @generated from field: repeated participant.v1.Participant participants = 1;
   */
  participants: Participant[];
};

/**
 * Describes the message participant.v1.GetParticipantsByTournamentIDResponse.
 * Use `create(GetParticipantsByTournamentIDResponseSchema)` to create a new message.
 */
export const GetParticipantsByTournamentIDResponseSchema: GenMessage<GetParticipantsByTournamentIDResponse> = /*@__PURE__*/
  messageDesc(file_participant_v1_participant_service, 1);

/**
 * @generated from service participant.v1.ParticipantService
 */
export const ParticipantService: GenService<{
  /**
   * @generated from rpc participant.v1.ParticipantService.GetParticipantsByTournamentID
   */
  getParticipantsByTournamentID: {
    methodKind: "unary";
    input: typeof GetParticipantsByTournamentIDRequestSchema;
    output: typeof GetParticipantsByTournamentIDResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_participant_v1_participant_service, 0);

