// @generated by protoc-gen-es v2.6.2 with parameter "target=ts,import_extension=none"
// @generated from file match/v1/match_service.proto (package match.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import { file_google_protobuf_wrappers } from "../../google/protobuf/wrappers_pb";
import type { Match } from "./match_pb";
import { file_match_v1_match } from "./match_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file match/v1/match_service.proto.
 */
export const file_match_v1_match_service: GenFile = /*@__PURE__*/
  fileDesc("ChxtYXRjaC92MS9tYXRjaF9zZXJ2aWNlLnByb3RvEghtYXRjaC52MSI+ChNHZXRNYXRjaEJ5SURSZXF1ZXN0EicKAmlkGAEgASgLMhsuZ29vZ2xlLnByb3RvYnVmLkludDY0VmFsdWUiNgoUR2V0TWF0Y2hCeUlEUmVzcG9uc2USHgoFbWF0Y2gYASABKAsyDy5tYXRjaC52MS5NYXRjaCJDChZHZW5lcmF0ZU1hdGNoZXNSZXF1ZXN0EhUKDXRvdXJuYW1lbnRfaWQYASABKAUSEgoKcGxheWVyX2lkcxgCIAMoCSI7ChdHZW5lcmF0ZU1hdGNoZXNSZXNwb25zZRIgCgdtYXRjaGVzGAEgAygLMg8ubWF0Y2gudjEuTWF0Y2gytQEKDE1hdGNoU2VydmljZRJNCgxHZXRNYXRjaEJ5SUQSHS5tYXRjaC52MS5HZXRNYXRjaEJ5SURSZXF1ZXN0Gh4ubWF0Y2gudjEuR2V0TWF0Y2hCeUlEUmVzcG9uc2USVgoPR2VuZXJhdGVNYXRjaGVzEiAubWF0Y2gudjEuR2VuZXJhdGVNYXRjaGVzUmVxdWVzdBohLm1hdGNoLnYxLkdlbmVyYXRlTWF0Y2hlc1Jlc3BvbnNlQidaJWJhY2tlbmQvaW50ZXJuYWwvZ2VuL21hdGNoL3YxO21hdGNocGJiBnByb3RvMw", [file_google_protobuf_wrappers, file_match_v1_match]);

/**
 * @generated from message match.v1.GetMatchByIDRequest
 */
export type GetMatchByIDRequest = Message<"match.v1.GetMatchByIDRequest"> & {
  /**
   * @generated from field: google.protobuf.Int64Value id = 1;
   */
  id?: bigint;
};

/**
 * Describes the message match.v1.GetMatchByIDRequest.
 * Use `create(GetMatchByIDRequestSchema)` to create a new message.
 */
export const GetMatchByIDRequestSchema: GenMessage<GetMatchByIDRequest> = /*@__PURE__*/
  messageDesc(file_match_v1_match_service, 0);

/**
 * @generated from message match.v1.GetMatchByIDResponse
 */
export type GetMatchByIDResponse = Message<"match.v1.GetMatchByIDResponse"> & {
  /**
   * @generated from field: match.v1.Match match = 1;
   */
  match?: Match;
};

/**
 * Describes the message match.v1.GetMatchByIDResponse.
 * Use `create(GetMatchByIDResponseSchema)` to create a new message.
 */
export const GetMatchByIDResponseSchema: GenMessage<GetMatchByIDResponse> = /*@__PURE__*/
  messageDesc(file_match_v1_match_service, 1);

/**
 * @generated from message match.v1.GenerateMatchesRequest
 */
export type GenerateMatchesRequest = Message<"match.v1.GenerateMatchesRequest"> & {
  /**
   * @generated from field: int32 tournament_id = 1;
   */
  tournamentId: number;

  /**
   * @generated from field: repeated string player_ids = 2;
   */
  playerIds: string[];
};

/**
 * Describes the message match.v1.GenerateMatchesRequest.
 * Use `create(GenerateMatchesRequestSchema)` to create a new message.
 */
export const GenerateMatchesRequestSchema: GenMessage<GenerateMatchesRequest> = /*@__PURE__*/
  messageDesc(file_match_v1_match_service, 2);

/**
 * @generated from message match.v1.GenerateMatchesResponse
 */
export type GenerateMatchesResponse = Message<"match.v1.GenerateMatchesResponse"> & {
  /**
   * @generated from field: repeated match.v1.Match matches = 1;
   */
  matches: Match[];
};

/**
 * Describes the message match.v1.GenerateMatchesResponse.
 * Use `create(GenerateMatchesResponseSchema)` to create a new message.
 */
export const GenerateMatchesResponseSchema: GenMessage<GenerateMatchesResponse> = /*@__PURE__*/
  messageDesc(file_match_v1_match_service, 3);

/**
 * @generated from service match.v1.MatchService
 */
export const MatchService: GenService<{
  /**
   * @generated from rpc match.v1.MatchService.GetMatchByID
   */
  getMatchByID: {
    methodKind: "unary";
    input: typeof GetMatchByIDRequestSchema;
    output: typeof GetMatchByIDResponseSchema;
  },
  /**
   * @generated from rpc match.v1.MatchService.GenerateMatches
   */
  generateMatches: {
    methodKind: "unary";
    input: typeof GenerateMatchesRequestSchema;
    output: typeof GenerateMatchesResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_match_v1_match_service, 0);

