// @generated by protoc-gen-es v2.11.0 with parameter "target=ts,import_extension=none"
// @generated from file match/v1/match.proto (package match.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Participant } from "../../participant/v1/participant_pb";
import { file_participant_v1_participant } from "../../participant/v1/participant_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file match/v1/match.proto.
 */
export const file_match_v1_match: GenFile = /*@__PURE__*/
  fileDesc("ChRtYXRjaC92MS9tYXRjaC5wcm90bxIIbWF0Y2gudjEiygIKBU1hdGNoEgoKAmlkGAEgASgJEhUKDWRpc3BsYXlfb3JkZXIYAiABKAUSEwoLbWF0Y2hfaW5kZXgYAyABKAUSDQoFcm91bmQYBCABKAUSFAoMdG90YWxfcm91bmRzGAUgASgFEgwKBHNpZGUYBiABKAkSDwoHcGxheWVycxgHIAMoCRIOCgZ3aW5uZXIYCCABKAkSEwoLaXNfYXV0b193aW4YCSABKAgSEgoKaXNfc2tpcHBlZBgKIAEoCBIhCgRkYXRhGAsgASgLMhMubWF0Y2gudjEuTWF0Y2hEYXRhEiQKCHBvc2l0aW9uGAwgASgLMhIubWF0Y2gudjEuUG9zaXRpb24SEAoIcm91bmRfaWQYDSABKAkSMQoMcGFydGljaXBhbnRzGA4gAygLMhsucGFydGljaXBhbnQudjEuUGFydGljaXBhbnQiGgoJTWF0Y2hEYXRhEg0KBWxhYmVsGAEgASgJIiAKCFBvc2l0aW9uEgkKAXgYASABKAUSCQoBeRgCIAEoBUInWiViYWNrZW5kL2ludGVybmFsL2dlbi9tYXRjaC92MTttYXRjaHBiYgZwcm90bzM", [file_participant_v1_participant]);

/**
 * @generated from message match.v1.Match
 */
export type Match = Message<"match.v1.Match"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: int32 display_order = 2;
   */
  displayOrder: number;

  /**
   * @generated from field: int32 match_index = 3;
   */
  matchIndex: number;

  /**
   * @generated from field: int32 round = 4;
   */
  round: number;

  /**
   * @generated from field: int32 total_rounds = 5;
   */
  totalRounds: number;

  /**
   * @generated from field: string side = 6;
   */
  side: string;

  /**
   * @generated from field: repeated string players = 7;
   */
  players: string[];

  /**
   * @generated from field: string winner = 8;
   */
  winner: string;

  /**
   * @generated from field: bool is_auto_win = 9;
   */
  isAutoWin: boolean;

  /**
   * @generated from field: bool is_skipped = 10;
   */
  isSkipped: boolean;

  /**
   * @generated from field: match.v1.MatchData data = 11;
   */
  data?: MatchData;

  /**
   * @generated from field: match.v1.Position position = 12;
   */
  position?: Position;

  /**
   * @generated from field: string round_id = 13;
   */
  roundId: string;

  /**
   * @generated from field: repeated participant.v1.Participant participants = 14;
   */
  participants: Participant[];
};

/**
 * Describes the message match.v1.Match.
 * Use `create(MatchSchema)` to create a new message.
 */
export const MatchSchema: GenMessage<Match> = /*@__PURE__*/
  messageDesc(file_match_v1_match, 0);

/**
 * @generated from message match.v1.MatchData
 */
export type MatchData = Message<"match.v1.MatchData"> & {
  /**
   * @generated from field: string label = 1;
   */
  label: string;
};

/**
 * Describes the message match.v1.MatchData.
 * Use `create(MatchDataSchema)` to create a new message.
 */
export const MatchDataSchema: GenMessage<MatchData> = /*@__PURE__*/
  messageDesc(file_match_v1_match, 1);

/**
 * @generated from message match.v1.Position
 */
export type Position = Message<"match.v1.Position"> & {
  /**
   * @generated from field: int32 x = 1;
   */
  x: number;

  /**
   * @generated from field: int32 y = 2;
   */
  y: number;
};

/**
 * Describes the message match.v1.Position.
 * Use `create(PositionSchema)` to create a new message.
 */
export const PositionSchema: GenMessage<Position> = /*@__PURE__*/
  messageDesc(file_match_v1_match, 2);

