// @generated by protoc-gen-es v2.6.2 with parameter "target=ts"
// @generated from file auth/v1/auth_service.proto (package auth.v1, syntax proto3)
/* eslint-disable */
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
/**
 * Describes the file auth/v1/auth_service.proto.
 */
export const file_auth_v1_auth_service = /*@__PURE__*/ fileDesc("ChphdXRoL3YxL2F1dGhfc2VydmljZS5wcm90bxIHYXV0aC52MSIcCgxMb2dpblJlcXVlc3QSDAoEdXNlchgBIAEoCSIjCg1Mb2dpblJlc3BvbnNlEhIKCmNzcmZfdG9rZW4YASABKAkyRQoLQXV0aFNlcnZpY2USNgoFTG9naW4SFS5hdXRoLnYxLkxvZ2luUmVxdWVzdBoWLmF1dGgudjEuTG9naW5SZXNwb25zZUIlWiNiYWNrZW5kL2ludGVybmFsL2dlbi9hdXRoL3YxO2F1dGhwYmIGcHJvdG8z");
/**
 * Describes the message auth.v1.LoginRequest.
 * Use `create(LoginRequestSchema)` to create a new message.
 */
export const LoginRequestSchema = /*@__PURE__*/ messageDesc(file_auth_v1_auth_service, 0);
/**
 * Describes the message auth.v1.LoginResponse.
 * Use `create(LoginResponseSchema)` to create a new message.
 */
export const LoginResponseSchema = /*@__PURE__*/ messageDesc(file_auth_v1_auth_service, 1);
/**
 * @generated from service auth.v1.AuthService
 */
export const AuthService = /*@__PURE__*/ serviceDesc(file_auth_v1_auth_service, 0);
