// @generated by protoc-gen-es v2.11.0 with parameter "target=ts,import_extension=none"
// @generated from file auth/v1/auth_service.proto (package auth.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file auth/v1/auth_service.proto.
 */
export const file_auth_v1_auth_service: GenFile = /*@__PURE__*/
  fileDesc("ChphdXRoL3YxL2F1dGhfc2VydmljZS5wcm90bxIHYXV0aC52MSIpChVBdXRoV2l0aEdvb2dsZVJlcXVlc3QSEAoIaWRfdG9rZW4YASABKAkiWgoWQXV0aHdpdGhHb29nbGVSZXNwb25zZRIUCgxhY2Nlc3NfdG9rZW4YASABKAkSFQoNcmVmcmVzaF90b2tlbhgCIAEoCRITCgtpc19uZXdfdXNlchgDIAEoCDJgCgtBdXRoU2VydmljZRJRCg5BdXRoV2l0aEdvb2dsZRIeLmF1dGgudjEuQXV0aFdpdGhHb29nbGVSZXF1ZXN0Gh8uYXV0aC52MS5BdXRod2l0aEdvb2dsZVJlc3BvbnNlQiVaI2JhY2tlbmQvaW50ZXJuYWwvZ2VuL2F1dGgvdjE7YXV0aHBiYgZwcm90bzM");

/**
 * @generated from message auth.v1.AuthWithGoogleRequest
 */
export type AuthWithGoogleRequest = Message<"auth.v1.AuthWithGoogleRequest"> & {
  /**
   * @generated from field: string id_token = 1;
   */
  idToken: string;
};

/**
 * Describes the message auth.v1.AuthWithGoogleRequest.
 * Use `create(AuthWithGoogleRequestSchema)` to create a new message.
 */
export const AuthWithGoogleRequestSchema: GenMessage<AuthWithGoogleRequest> = /*@__PURE__*/
  messageDesc(file_auth_v1_auth_service, 0);

/**
 * @generated from message auth.v1.AuthwithGoogleResponse
 */
export type AuthwithGoogleResponse = Message<"auth.v1.AuthwithGoogleResponse"> & {
  /**
   * @generated from field: string access_token = 1;
   */
  accessToken: string;

  /**
   * @generated from field: string refresh_token = 2;
   */
  refreshToken: string;

  /**
   * @generated from field: bool is_new_user = 3;
   */
  isNewUser: boolean;
};

/**
 * Describes the message auth.v1.AuthwithGoogleResponse.
 * Use `create(AuthwithGoogleResponseSchema)` to create a new message.
 */
export const AuthwithGoogleResponseSchema: GenMessage<AuthwithGoogleResponse> = /*@__PURE__*/
  messageDesc(file_auth_v1_auth_service, 1);

/**
 * @generated from service auth.v1.AuthService
 */
export const AuthService: GenService<{
  /**
   * @generated from rpc auth.v1.AuthService.AuthWithGoogle
   */
  authWithGoogle: {
    methodKind: "unary";
    input: typeof AuthWithGoogleRequestSchema;
    output: typeof AuthwithGoogleResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_auth_v1_auth_service, 0);

