// @generated by protoc-gen-es v2.12.1 with parameter "target=ts,import_extension=none"
// @generated from file round/v1/round.proto (package round.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Match } from "../../match/v1/match_pb";
import { file_match_v1_match } from "../../match/v1/match_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file round/v1/round.proto.
 */
export const file_round_v1_round: GenFile = /*@__PURE__*/
  fileDesc("ChRyb3VuZC92MS9yb3VuZC5wcm90bxIIcm91bmQudjEilwEKBVJvdW5kEgoKAmlkGAEgASgJEgwKBG5hbWUYAiABKAkSIAoHbWF0Y2hlcxgDIAMoCzIPLm1hdGNoLnYxLk1hdGNoEhIKCmJyYWNrZXRfaWQYBCABKAkSDwoHcmFjZV90bxgFIAEoBRIYChBlbGltaW5hdGlvbl90eXBlGAYgASgJEhMKC29yZGVyX2luZGV4GAcgASgFQidaJWJhY2tlbmQvaW50ZXJuYWwvZ2VuL3JvdW5kL3YxO3JvdW5kcGJiBnByb3RvMw", [file_match_v1_match]);

/**
 * @generated from message round.v1.Round
 */
export type Round = Message<"round.v1.Round"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * @generated from field: repeated match.v1.Match matches = 3;
   */
  matches: Match[];

  /**
   * @generated from field: string bracket_id = 4;
   */
  bracketId: string;

  /**
   * @generated from field: int32 race_to = 5;
   */
  raceTo: number;

  /**
   * @generated from field: string elimination_type = 6;
   */
  eliminationType: string;

  /**
   * @generated from field: int32 order_index = 7;
   */
  orderIndex: number;
};

/**
 * Describes the message round.v1.Round.
 * Use `create(RoundSchema)` to create a new message.
 */
export const RoundSchema: GenMessage<Round> = /*@__PURE__*/
  messageDesc(file_round_v1_round, 0);

