// @generated by protoc-gen-es v2.12.1 with parameter "target=ts,import_extension=none"
// @generated from file round/v1/round_service.proto (package round.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { Round } from "./round_pb";
import { file_round_v1_round } from "./round_pb";
import type { EmptySchema } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_empty } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file round/v1/round_service.proto.
 */
export const file_round_v1_round_service: GenFile = /*@__PURE__*/
  fileDesc("Chxyb3VuZC92MS9yb3VuZF9zZXJ2aWNlLnByb3RvEghyb3VuZC52MSJOChRSZXBsYWNlUm91bmRzUmVxdWVzdBIVCg10b3VybmFtZW50X2lkGAEgASgJEh8KBnJvdW5kcxgCIAMoCzIPLnJvdW5kLnYxLlJvdW5kMlcKDFJvdW5kU2VydmljZRJHCg1SZXBsYWNlUm91bmRzEh4ucm91bmQudjEuUmVwbGFjZVJvdW5kc1JlcXVlc3QaFi5nb29nbGUucHJvdG9idWYuRW1wdHlCJ1olYmFja2VuZC9pbnRlcm5hbC9nZW4vcm91bmQvdjE7cm91bmRwYmIGcHJvdG8z", [file_round_v1_round, file_google_protobuf_empty]);

/**
 * @generated from message round.v1.ReplaceRoundsRequest
 */
export type ReplaceRoundsRequest = Message<"round.v1.ReplaceRoundsRequest"> & {
  /**
   * @generated from field: string tournament_id = 1;
   */
  tournamentId: string;

  /**
   * @generated from field: repeated round.v1.Round rounds = 2;
   */
  rounds: Round[];
};

/**
 * Describes the message round.v1.ReplaceRoundsRequest.
 * Use `create(ReplaceRoundsRequestSchema)` to create a new message.
 */
export const ReplaceRoundsRequestSchema: GenMessage<ReplaceRoundsRequest> = /*@__PURE__*/
  messageDesc(file_round_v1_round_service, 0);

/**
 * @generated from service round.v1.RoundService
 */
export const RoundService: GenService<{
  /**
   * @generated from rpc round.v1.RoundService.ReplaceRounds
   */
  replaceRounds: {
    methodKind: "unary";
    input: typeof ReplaceRoundsRequestSchema;
    output: typeof EmptySchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_round_v1_round_service, 0);

