// @generated by protoc-gen-es v2.12.1 with parameter "target=ts,import_extension=none"
// @generated from file round/v1/round.proto (package round.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Match } from "../../match/v1/match_pb";
import { file_match_v1_match } from "../../match/v1/match_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file round/v1/round.proto.
 */
export const file_round_v1_round: GenFile = /*@__PURE__*/
  fileDesc("ChRyb3VuZC92MS9yb3VuZC5wcm90bxIIcm91bmQudjEisgEKBVJvdW5kEgoKAmlkGAEgASgJEgwKBG5hbWUYAiABKAkSIAoHbWF0Y2hlcxgDIAMoCzIPLm1hdGNoLnYxLk1hdGNoEhIKCmJyYWNrZXRfaWQYBCABKAkSDwoHcmFjZV90bxgFIAEoBRIzChBlbGltaW5hdGlvbl90eXBlGAYgASgOMhkucm91bmQudjEuRWxpbWluYXRpb25UeXBlEhMKC29yZGVyX2luZGV4GAcgASgFKikKD0VsaW1pbmF0aW9uVHlwZRIKCgZTSU5HTEUQABIKCgZET1VCTEUQAUInWiViYWNrZW5kL2ludGVybmFsL2dlbi9yb3VuZC92MTtyb3VuZHBiYgZwcm90bzM", [file_match_v1_match]);

/**
 * @generated from message round.v1.Round
 */
export type Round = Message<"round.v1.Round"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * @generated from field: repeated match.v1.Match matches = 3;
   */
  matches: Match[];

  /**
   * @generated from field: string bracket_id = 4;
   */
  bracketId: string;

  /**
   * @generated from field: int32 race_to = 5;
   */
  raceTo: number;

  /**
   * @generated from field: round.v1.EliminationType elimination_type = 6;
   */
  eliminationType: EliminationType;

  /**
   * @generated from field: int32 order_index = 7;
   */
  orderIndex: number;
};

/**
 * Describes the message round.v1.Round.
 * Use `create(RoundSchema)` to create a new message.
 */
export const RoundSchema: GenMessage<Round> = /*@__PURE__*/
  messageDesc(file_round_v1_round, 0);

/**
 * @generated from enum round.v1.EliminationType
 */
export enum EliminationType {
  /**
   * @generated from enum value: SINGLE = 0;
   */
  SINGLE = 0,

  /**
   * @generated from enum value: DOUBLE = 1;
   */
  DOUBLE = 1,
}

/**
 * Describes the enum round.v1.EliminationType.
 */
export const EliminationTypeSchema: GenEnum<EliminationType> = /*@__PURE__*/
  enumDesc(file_round_v1_round, 0);

