// @generated by protoc-gen-es v2.6.2 with parameter "target=ts,import_extension=none"
// @generated from file player/v1/player_service.proto (package player.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import { file_google_protobuf_timestamp } from "../../google/protobuf/timestamp_pb";
import { file_google_protobuf_wrappers } from "@bufbuild/protobuf/wkt";
import type { EmptySchema } from "../../google/protobuf/empty_pb";
import { file_google_protobuf_empty } from "../../google/protobuf/empty_pb";
import type { Player } from "./player_pb";
import { file_player_v1_player } from "./player_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file player/v1/player_service.proto.
 */
export const file_player_v1_player_service: GenFile = /*@__PURE__*/
  fileDesc("Ch5wbGF5ZXIvdjEvcGxheWVyX3NlcnZpY2UucHJvdG8SCXBsYXllci52MSI3ChFHZXRQbGF5ZXJSZXNwb25zZRIiCgdwbGF5ZXJzGAEgAygLMhEucGxheWVyLnYxLlBsYXllcjJSCg1QbGF5ZXJTZXJ2aWNlEkEKCUdldFBsYXllchIWLmdvb2dsZS5wcm90b2J1Zi5FbXB0eRocLnBsYXllci52MS5HZXRQbGF5ZXJSZXNwb25zZUIpWidiYWNrZW5kL2ludGVybmFsL2dlbi9wbGF5ZXIvdjE7cGxheWVycGJiBnByb3RvMw", [file_google_protobuf_timestamp, file_google_protobuf_wrappers, file_google_protobuf_empty, file_player_v1_player]);

/**
 * @generated from message player.v1.GetPlayerResponse
 */
export type GetPlayerResponse = Message<"player.v1.GetPlayerResponse"> & {
  /**
   * @generated from field: repeated player.v1.Player players = 1;
   */
  players: Player[];
};

/**
 * Describes the message player.v1.GetPlayerResponse.
 * Use `create(GetPlayerResponseSchema)` to create a new message.
 */
export const GetPlayerResponseSchema: GenMessage<GetPlayerResponse> = /*@__PURE__*/
  messageDesc(file_player_v1_player_service, 0);

/**
 * @generated from service player.v1.PlayerService
 */
export const PlayerService: GenService<{
  /**
   * @generated from rpc player.v1.PlayerService.GetPlayer
   */
  getPlayer: {
    methodKind: "unary";
    input: typeof EmptySchema;
    output: typeof GetPlayerResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_player_v1_player_service, 0);

