// @generated by protoc-gen-es v2.6.2 with parameter "target=ts,import_extension=none"
// @generated from file player/v1/player.proto (package player.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_google_protobuf_wrappers } from "@bufbuild/protobuf/wkt";
import { file_buf_validate_validate } from "../../buf/validate/validate_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file player/v1/player.proto.
 */
export const file_player_v1_player: GenFile = /*@__PURE__*/
  fileDesc("ChZwbGF5ZXIvdjEvcGxheWVyLnByb3RvEglwbGF5ZXIudjEitQIKBlBsYXllchIvCgJpZBgBIAEoCzIbLmdvb2dsZS5wcm90b2J1Zi5JbnQ2NFZhbHVlQga6SAPIAQESMgoEbmFtZRgCIAEoCzIcLmdvb2dsZS5wcm90b2J1Zi5TdHJpbmdWYWx1ZUIGukgDyAEBEi0KB2NvdW50cnkYAyABKAsyHC5nb29nbGUucHJvdG9idWYuU3RyaW5nVmFsdWUSMwoFcGhvbmUYBCABKAsyHC5nb29nbGUucHJvdG9idWYuU3RyaW5nVmFsdWVCBrpIA8gBARIxCgNwaWQYBSABKAsyHC5nb29nbGUucHJvdG9idWYuU3RyaW5nVmFsdWVCBrpIA8gBARIvCgljcmVhdGVfYXQYBiABKAsyHC5nb29nbGUucHJvdG9idWYuU3RyaW5nVmFsdWVCKVonYmFja2VuZC9pbnRlcm5hbC9nZW4vcGxheWVyL3YxO3BsYXllcnBiYgZwcm90bzM", [file_google_protobuf_wrappers, file_buf_validate_validate]);

/**
 * @generated from message player.v1.Player
 */
export type Player = Message<"player.v1.Player"> & {
  /**
   * @generated from field: google.protobuf.Int64Value id = 1;
   */
  id?: bigint;

  /**
   * @generated from field: google.protobuf.StringValue name = 2;
   */
  name?: string;

  /**
   * @generated from field: google.protobuf.StringValue country = 3;
   */
  country?: string;

  /**
   * @generated from field: google.protobuf.StringValue phone = 4;
   */
  phone?: string;

  /**
   * @generated from field: google.protobuf.StringValue pid = 5;
   */
  pid?: string;

  /**
   * @generated from field: google.protobuf.StringValue create_at = 6;
   */
  createAt?: string;
};

/**
 * Describes the message player.v1.Player.
 * Use `create(PlayerSchema)` to create a new message.
 */
export const PlayerSchema: GenMessage<Player> = /*@__PURE__*/
  messageDesc(file_player_v1_player, 0);

