// @generated by protoc-gen-es v2.11.0 with parameter "target=ts,import_extension=none"
// @generated from file bracket/v1/bracket.proto (package bracket.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Round } from "../../round/v1/round_pb";
import { file_round_v1_round } from "../../round/v1/round_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file bracket/v1/bracket.proto.
 */
export const file_bracket_v1_bracket: GenFile = /*@__PURE__*/
  fileDesc("ChhicmFja2V0L3YxL2JyYWNrZXQucHJvdG8SCmJyYWNrZXQudjEiRAoHQnJhY2tldBIKCgJpZBgBIAEoCRIMCgRuYW1lGAIgASgJEh8KBnJvdW5kcxgDIAMoCzIPLnJvdW5kLnYxLlJvdW5kQitaKWJhY2tlbmQvaW50ZXJuYWwvZ2VuL2JyYWNrZXQvdjE7YnJhY2tldHBiYgZwcm90bzM", [file_round_v1_round]);

/**
 * @generated from message bracket.v1.Bracket
 */
export type Bracket = Message<"bracket.v1.Bracket"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * @generated from field: repeated round.v1.Round rounds = 3;
   */
  rounds: Round[];
};

/**
 * Describes the message bracket.v1.Bracket.
 * Use `create(BracketSchema)` to create a new message.
 */
export const BracketSchema: GenMessage<Bracket> = /*@__PURE__*/
  messageDesc(file_bracket_v1_bracket, 0);

