// @generated by protoc-gen-es v2.11.0 with parameter "target=ts,import_extension=none"
// @generated from file session/v1/session.proto (package session.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file session/v1/session.proto.
 */
export const file_session_v1_session: GenFile = /*@__PURE__*/
  fileDesc("ChhzZXNzaW9uL3YxL3Nlc3Npb24ucHJvdG8SCnNlc3Npb24udjEi8wEKB1Nlc3Npb24SCgoCaWQYASABKAkSDwoHdXNlcl9pZBgCIAEoCRIaChJyZWZyZXNoX3Rva2VuX2hhc2gYAyABKAkSFwoPdG9rZW5fZmFtaWx5X2lkGAQgASgJEhIKCmV4cGlyZXNfYXQYBSABKAkSGwoTYWJzb2x1dGVfZXhwaXJlc19hdBgGIAEoCRISCgpjcmVhdGVkX2F0GAcgASgJEhIKCnJvdGF0ZWRfYXQYCCABKAkSFAoMbGFzdF91c2VkX2F0GAkgASgJEg8KB3Jldm9rZWQYCiABKAgSFgoOaXNfY29tcHJvbWlzZWQYCyABKAhCK1opYmFja2VuZC9pbnRlcm5hbC9nZW4vc2Vzc2lvbi92MTtzZXNzaW9ucGJiBnByb3RvMw", [file_google_protobuf_timestamp]);

/**
 * @generated from message session.v1.Session
 */
export type Session = Message<"session.v1.Session"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string user_id = 2;
   */
  userId: string;

  /**
   * @generated from field: string refresh_token_hash = 3;
   */
  refreshTokenHash: string;

  /**
   * @generated from field: string token_family_id = 4;
   */
  tokenFamilyId: string;

  /**
   * @generated from field: string expires_at = 5;
   */
  expiresAt: string;

  /**
   * @generated from field: string absolute_expires_at = 6;
   */
  absoluteExpiresAt: string;

  /**
   * @generated from field: string created_at = 7;
   */
  createdAt: string;

  /**
   * @generated from field: string rotated_at = 8;
   */
  rotatedAt: string;

  /**
   * @generated from field: string last_used_at = 9;
   */
  lastUsedAt: string;

  /**
   * @generated from field: bool revoked = 10;
   */
  revoked: boolean;

  /**
   * @generated from field: bool is_compromised = 11;
   */
  isCompromised: boolean;
};

/**
 * Describes the message session.v1.Session.
 * Use `create(SessionSchema)` to create a new message.
 */
export const SessionSchema: GenMessage<Session> = /*@__PURE__*/
  messageDesc(file_session_v1_session, 0);

